version: 0.2

phases:
  install:
    commands:
      - echo Hello install
  build:
    commands:
      - echo Prining directory...
      - pwd
      - echo Prining directory...
      - npm install
      - npm run build
