# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
version: 0.2

phases:
  install:
    # runtime-versions:
    #   java: corretto8
    #   python: 3.x
    #   ruby: "$MY_RUBY_VAR"
    commands:
      - echo Hello install
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Prining directory...
      - pwd
      - echo Prining directory...
      - npm run build
  # post_build:
  #   commands:
  #     - aws s3 sync ./build s3://reactci --delete --acl public-read	
