version: 0.2

phases:
  install:
    commands:
      - echo Hello install
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Prining directory...
      - pwd
      - echo Prining directory...
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build s3://reactci --delete --acl public-read	
