version: 0.2

phases:
  install:
    commands:
      - echo Hello install
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Prining directory...
      - pwd
      - echo Prining directory...
      - npm run build
  post_build:
    commands:
      - echo Testing S3 access...
      - aws s3 ls s3://reactci
      - echo Testing S3 access...
